import { useState, useEffect } from "react";
// LAYOUTS
import { Navbar, Footer } from "./index";
// NEXT
import Head from "next/head";
// Styles
import styles from "./Layout.module.css";

//////////////////// EXPORT FUNCTION ////////////////////
export default function Layout({ children }) {
  //////////////////// EFFECT TRANSITIONS PAGES ////////////////////
  const [displayChildren, setDisplayChildren] = useState(children);
  const [transitionStage, setTransitionStage] = useState("fadeOut");
  useEffect(() => {
    setTransitionStage("fadeIn");
  }, []);

  useEffect(() => {
    if (children !== displayChildren) setTransitionStage("fadeOut");
  }, [children, setDisplayChildren, displayChildren]);

  //////////////////// RETURN ////////////////////
  return (
    <div>
      <Head>
        <title>Clone NextFlix</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div
        onTransitionEnd={() => {
          if (transitionStage === "fadeOut") {
            console.log("fading out");
            setDisplayChildren(children);
            setTransitionStage("fadeIn");
          }
        }}
        className={`${styles.content} ${styles[transitionStage]}`}
      >
        {displayChildren}
      </div>
      <Footer />
    </div>
  );
}
